//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankoATRBPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLANKO
    {
        public BLANKO()
        {
            this.PENGELOLAAN_BLANKO = new HashSet<PENGELOLAAN_BLANKO>();
        }
    
        public string BLANKOID { get; set; }
        public string SERI { get; set; }
        public Nullable<short> TAHUN { get; set; }
        public string STATUS { get; set; }
        public string BERKASID { get; set; }
        public Nullable<System.DateTime> TANGGALSISIP { get; set; }
        public string PETUGASSISIP { get; set; }
        public string KANTORID { get; set; }
        public string PENGAMBIL { get; set; }
        public string DI301 { get; set; }
        public string DI208 { get; set; }
        public string DI301A { get; set; }
        public string NOMORHAK { get; set; }
        public Nullable<System.DateTime> TANGGALHAK { get; set; }
        public Nullable<System.DateTime> TANGGALPEMBUKUAN { get; set; }
        public Nullable<System.DateTime> TANGGALPENYERAHAN { get; set; }
        public Nullable<System.DateTime> TANGGALSUNTING { get; set; }
        public string PETUGASSUNTING { get; set; }
        public string TIPE { get; set; }
        public string DI307 { get; set; }
        public Nullable<System.DateTime> TANGGALSELESAISPP { get; set; }
        public string BERITAACARAPEMBATALANID { get; set; }
        public string BERITAACARAPENYERAHANID { get; set; }
        public Nullable<System.DateTime> TANGGALSINKRONISASI { get; set; }
        public Nullable<decimal> VERSI { get; set; }
        public Nullable<System.DateTime> TANGGALPERUBAHAN { get; set; }
        public string STATUSHAPUS { get; set; }
        public string USERHAPUS { get; set; }
        public string BERITAACARAPENGEMBALIANID { get; set; }
        public Nullable<decimal> STATUSKOREKSIKANWIL { get; set; }
        public Nullable<decimal> STATUSKOREKSIKANTAH { get; set; }
        public Nullable<decimal> POSITION { get; set; }
        public string DISTRIBUTION_ID { get; set; }
        public string BERITAACARAPENYERAHANIDKNTH { get; set; }
    
        public virtual ICollection<PENGELOLAAN_BLANKO> PENGELOLAAN_BLANKO { get; set; }
    }
}
