//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankoATRBPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KANTOR
    {
        public KANTOR()
        {
            this.USERPERORANGANs = new HashSet<USERPERORANGAN>();
        }
    
        public string KANTORID { get; set; }
        public string KODE { get; set; }
        public string NAMA { get; set; }
        public string KOTA { get; set; }
        public string ALAMAT { get; set; }
        public string TELEPON { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> VALIDSEJAK { get; set; }
        public Nullable<System.DateTime> VALIDSAMPAI { get; set; }
        public Nullable<decimal> HSBKU1 { get; set; }
        public Nullable<decimal> HSBKU2 { get; set; }
        public Nullable<decimal> HSBKPA1 { get; set; }
        public Nullable<decimal> HSBKPA2 { get; set; }
        public Nullable<decimal> HSBKPP1 { get; set; }
        public Nullable<decimal> HSBKPP2 { get; set; }
        public Nullable<decimal> HSBKPM1 { get; set; }
        public Nullable<decimal> HSBKPM2 { get; set; }
        public Nullable<decimal> HSBKPB { get; set; }
        public string PEMBULATANLUAS { get; set; }
        public string KODESK { get; set; }
        public Nullable<short> TANGGALAWAL { get; set; }
        public string BULANAWAL { get; set; }
        public Nullable<short> TANGGALAKHIR { get; set; }
        public string BULANAKHIR { get; set; }
        public string INDUK { get; set; }
        public Nullable<short> TIPEKANTORID { get; set; }
        public Nullable<System.DateTime> TGLSK_PEMERIKSA { get; set; }
        public string NOSK_PEMERIKSA { get; set; }
        public Nullable<System.DateTime> TANGGALMULAI { get; set; }
        public string TIPEKONEKSI { get; set; }
        public string NAMAPROVIDER { get; set; }
        public string BANDWIDTH { get; set; }
        public string TIPOLOGI { get; set; }
        public string REGIONAL { get; set; }
        public string DIREKTORI { get; set; }
        public string APLIKASI { get; set; }
        public Nullable<decimal> PAGUBERKASONLINE { get; set; }
        public Nullable<decimal> EXPIREBERKASONLINE { get; set; }
        public Nullable<decimal> STATUSMINTABT { get; set; }
        public string TIPEPETADASAR { get; set; }
        public Nullable<decimal> SMSBERKASSELESAI { get; set; }
        public Nullable<decimal> SMSUMUMSELESAI { get; set; }
        public Nullable<decimal> SMSNODESELESAI { get; set; }
        public Nullable<decimal> SERTIPIKATSELEMBAR { get; set; }
        public Nullable<decimal> SIMPONIONLINE { get; set; }
        public string BAGIANAPP_BLANKO { get; set; }
        public string KODESATKER { get; set; }
        public Nullable<decimal> JUALBELIKHUSUS { get; set; }
        public Nullable<decimal> NILAIPRODA { get; set; }
        public Nullable<decimal> STATUSLAT { get; set; }
        public Nullable<decimal> PEMBAGIANAPP_BLANKOPUSAT { get; set; }
        public Nullable<int> LUASKM2 { get; set; }
        public string SUMBERLUAS { get; set; }
        public string NAMAALIAS { get; set; }
        public string LAYER_GISTARU { get; set; }
        public string URL_GISTARU { get; set; }
        public byte[] PASSPHRASE { get; set; }
        public string SUBSCRIBERID { get; set; }
        public string USERINSERT { get; set; }
        public Nullable<System.DateTime> INSERTDATE { get; set; }
        public string TTDID { get; set; }
        public string BERITAACARAID { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
    
        public virtual ICollection<USERPERORANGAN> USERPERORANGANs { get; set; }
    }
}
