//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankoATRBPN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BERITA_ACARA> BERITA_ACARA { get; set; }
        public DbSet<BLANKO> BLANKOes { get; set; }
        public DbSet<KANTOR> KANTORs { get; set; }
        public DbSet<PENGELOLAAN_BLANKO> PENGELOLAAN_BLANKO { get; set; }
        public DbSet<STATUS_PENGELOLAAN_BLANKO> STATUS_PENGELOLAAN_BLANKO { get; set; }
        public DbSet<TIPE_BLANKO> TIPE_BLANKO { get; set; }
        public DbSet<TIPE_PROSES_BLANKO> TIPE_PROSES_BLANKO { get; set; }
        public DbSet<USERPERORANGAN> USERPERORANGANs { get; set; }
        public DbSet<VPENGELOLAAN_BLANKO> VPENGELOLAAN_BLANKO { get; set; }
    }
}
