//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankoATRBPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_PENGELOLAAN_BLANKO
    {
        public STATUS_PENGELOLAAN_BLANKO()
        {
            this.PENGELOLAAN_BLANKO = new HashSet<PENGELOLAAN_BLANKO>();
        }
    
        public decimal STATUS_PENGELOLAAN_BLANKO_ID { get; set; }
        public string NAMA_STATUS { get; set; }
    
        public virtual ICollection<PENGELOLAAN_BLANKO> PENGELOLAAN_BLANKO { get; set; }
    }
}
