//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankoATRBPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPE_BLANKO
    {
        public TIPE_BLANKO()
        {
            this.PENGELOLAAN_BLANKO = new HashSet<PENGELOLAAN_BLANKO>();
        }
    
        public decimal TIPE_BLANKO_ID { get; set; }
        public string TIPE_BLANKO_CODE { get; set; }
        public string TIPE_BLANKO_NAME { get; set; }
        public string TIPE_BLANKO_DESCRIPTION { get; set; }
        public Nullable<decimal> TIPE_BLANKO_STATUS { get; set; }
        public Nullable<decimal> TIPE_BLANKO_CREATE_BY { get; set; }
        public Nullable<System.DateTime> TIPE_BLANKO_CREATE_DATE { get; set; }
        public Nullable<decimal> TIPE_BLANKO_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> TIPE_BLANKO_UPDATE_DATE { get; set; }
    
        public virtual ICollection<PENGELOLAAN_BLANKO> PENGELOLAAN_BLANKO { get; set; }
    }
}
