//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankoATRBPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERPERORANGAN
    {
        public USERPERORANGAN()
        {
            this.PENGELOLAAN_BLANKO = new HashSet<PENGELOLAAN_BLANKO>();
        }
    
        public string USERPERORANGANID { get; set; }
        public Nullable<System.DateTime> TANGGALDAFTAR { get; set; }
        public string NAMA { get; set; }
        public string NOMORIDENTITAS { get; set; }
        public string TEMPATLAHIR { get; set; }
        public Nullable<System.DateTime> TANGGALLAHIR { get; set; }
        public string EMAIL { get; set; }
        public string STATUSHAPUS { get; set; }
        public string USERHAPUS { get; set; }
        public string URLPROFILE { get; set; }
        public string NOMORHP { get; set; }
        public string JENISKELAMIN { get; set; }
        public string ALAMAT { get; set; }
        public string STATUS { get; set; }
        public string STATUSVALIDASI { get; set; }
        public Nullable<System.DateTime> TANGGALVALIDASI { get; set; }
        public string STATUSVERIFIKASI { get; set; }
        public Nullable<System.DateTime> TANGGALVERIFIKASI { get; set; }
        public Nullable<System.DateTime> VALIDSEJAK { get; set; }
        public Nullable<System.DateTime> VALIDSAMPAI { get; set; }
        public string RTRW { get; set; }
        public string KODEPOS { get; set; }
        public string KODEKONFIRMASI { get; set; }
        public string PEKERJAAN { get; set; }
        public string KODEUSER { get; set; }
        public string STATUSMIGRASI { get; set; }
        public string NPWP { get; set; }
        public string AKUNPERTANAHAN { get; set; }
        public string REFERENSIID { get; set; }
        public string URLFOTOIDENTITAS { get; set; }
        public string URLFOTOSELFIE { get; set; }
        public string JENISIDENTITAS { get; set; }
        public string KEWARGANEGARAAN { get; set; }
        public string KANTORID { get; set; }
        public string WILAYAHID { get; set; }
        public string KOTA { get; set; }
        public string STATUSAKTIVASI { get; set; }
        public Nullable<System.DateTime> TANGGALAKTIVASI { get; set; }
        public string USERAKTIVASI { get; set; }
        public string KANTORAKTIVASI { get; set; }
        public Nullable<System.DateTime> VALIDSEJAKPETUGASPM { get; set; }
        public Nullable<System.DateTime> VALIDSAMPAIPETUGASPM { get; set; }
        public Nullable<System.DateTime> TANGGALPETUGASPM { get; set; }
        public string USERPETUGASPM { get; set; }
        public string KANTORPETUGASPM { get; set; }
        public string ALASANPERURI { get; set; }
        public string STATUSKAWIN { get; set; }
        public Nullable<short> ISPERURI { get; set; }
        public Nullable<decimal> ANOMALI { get; set; }
        public Nullable<System.DateTime> TANGGALANOMALI { get; set; }
        public string EMAILLOWER { get; set; }
    
        public virtual KANTOR KANTOR { get; set; }
        public virtual ICollection<PENGELOLAAN_BLANKO> PENGELOLAAN_BLANKO { get; set; }
    }
}
