//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankoATRBPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPENGELOLAAN_BLANKO
    {
        public decimal PENGELOLAAN_BLANKO_ID { get; set; }
        public Nullable<System.DateTime> TANGGAL { get; set; }
        public string BLANKO { get; set; }
        public string TIPE_BLANKO { get; set; }
        public string BERITAACARAFILE { get; set; }
        public string NAMA_STATUS { get; set; }
    }
}
