--------------------------------------------------------
--  File created - Tuesday-October-25-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View VPENGELOLAAN_BLANKO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ATRBPN"."VPENGELOLAAN_BLANKO" ("PENGELOLAAN_BLANKO_ID", "TANGGAL", "BLANKO", "TIPE_BLANKO", "BERITAACARAFILE", "NAMA_STATUS") AS 
  SELECT 
    pb1.PENGELOLAAN_BLANKO_ID as PENGELOLAAN_BLANKO_ID, 
    pb1.TANGGAL_PEMBUATAN AS tanggal,
    b.SERI as blanko,
    tb.TIPE_BLANKO_NAME as tipe_blanko,
    ba.FILE_NAME as beritaAcaraFile,
    SPB.NAMA_STATUS
FROM 
    ATRBPN.PENGELOLAAN_BLANKO pb1 LEFT JOIN 
    BERITA_ACARA ba ON pb1.BERITA_ACARA_ID = ba.BERITA_ACARA_ID LEFT JOIN 
    TIPE_BLANKO tb ON pb1.TIPE_BLANKO_ID = tb.TIPE_BLANKO_ID LEFT JOIN
    TIPE_PROSES_BLANKO tpb ON pb1.TIPE_PROSES_BLANKO_ID  = tpb.TIPE_PROSES_BLANKO_ID LEFT JOIN 
    STATUS_PENGELOLAAN_BLANKO spb ON pb1.STATUS_PENGELOLAAN_BLANKO_ID = spb.STATUS_PENGELOLAAN_BLANKO_ID LEFT JOIN 
    BLANKO b ON pb1.BLANKOID = b.BLANKOID LEFT JOIN 
    USERPERORANGAN u ON pb1.USERPERORANGANID = u.USERPERORANGANID 
WHERE 
    pb1.PENGELOLAAN_BLANKO_ID = (SELECT MAX(pb2.PENGELOLAAN_BLANKO_ID) FROM ATRBPN.PENGELOLAAN_BLANKO pb2
WHERE pb2.BLANKOID = pb1.BLANKOID AND pb2.TIPE_PROSES_BLANKO_ID = 4)
;
